### ISSUE TITLE
[Java/Spark] JNI dispatcher thread causes ClassNotFoundException and prevents JVM shutdown

### ISSUE THREAD

**Issue by summaryzb** [lancedb/lance#6577]
## Summary
  When using lance-java inside Apache Spark executors, two related JNI threading issues cause failures:

  1. **ClassNotFoundException on the dispatcher thread** — the lance JNI dispatcher thread cannot find `org.lance.ipc.AsyncScanner`
  2. **Spark process never exits** — the dispatcher thread keeps the JVM alive indefinitely after the Spark task completes

  Both stem from the same root cause: the `lance-jni-dispatcher` thread is a native thread attached to the JVM via `attach_current_thread_permanently()`, which gives it the wrong classloader **and** marks it as a non-daemon thread.

  ## Error log
```
  thread 'lance-jni-dispatcher' panicked at src/dispatcher.rs:44:22:
  AsyncScanner class not found: JavaException
  java.lang.NoClassDefFoundError: org/lance/ipc/AsyncScanner
  Caused by: java.lang.ClassNotFoundException: org.lance.ipc.AsyncScanner
```

**Comment by summaryzb** [comment]
Introduced since https://github.com/lance-format/lance/pull/6102

**Comment by Xuanwo** [comment]
Closing as completed. The JNI dispatcher uses a cached `GlobalRef` and attaches as a daemon, with custom-classloader coverage for both `ClassNotFoundException` and JVM shutdown behavior.
