### ISSUE TITLE
ci: ethnum 1.5.2 fails to compile on Rust nightly >= 1.97.0

### ISSUE THREAD

**Issue by jackye1995** [lancedb/lance#6573]
## Problem

The `ethnum` crate (v1.5.2) fails to compile on Rust nightly >= 1.97.0 (circa 2026-04-01+) due to a `TryFromIntError` layout change in the standard library.

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> ethnum-1.5.2/src/error.rs:16:14
   |
16 |     unsafe { mem::transmute(()) }
   |              ^^^^^^^^^^^^^^
   |
   = note: source type: `()` (0 bits)
   = note: target type: `TryFromIntError` (8 bits)
```

## Dependency Chain

```
ethnum 1.5.2 <- jsonb 0.5.6 <- lance-arrow
```

## Impact

This breaks the coverage CI job which uses `cargo +nightly llvm-cov`. Regular stable builds (1.94.0) are unaffected.

## Current Workaround

Pinned nightly to `nightly-2026-03-31` (rustc 1.96.0-nightly) in `.github/workflows/rust.yml`.

## Upstream Status

- `ethnum` has not released a fix: https://github.com/nlordell/ethnum-rs
- `jsonb` still depends on `ethnum 1.5.2`: https://github.com/databendlabs/jsonb

## Resolution

Track upstream fix in `ethnum` and unpin nightly once a fixed version is released.

**Comment by jackye1995** [comment]
@LuciferYang thanks for the temporary fix. I published https://github.com/nlordell/ethnum-rs/pull/59

**Comment by jackye1995** [comment]
lol looks like you beat me again @LuciferYang , I closed mine, let's track https://github.com/nlordell/ethnum-rs/pull/58 then for the fix and upgrade

**Comment by LuciferYang** [comment]
Sure, I will keep an eye on the progress of https://github.com/nlordell/ethnum-rs/pull/58.

**Comment by Xuanwo** [comment]
Closing this as completed. Current main uses ethnum 1.5.3 and no longer carries the nightly pin used to work around the ethnum 1.5.2 compiler failure. @jackye1995, please reopen with a current compiler and dependency reproduction if the failure returns.
